name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 009160047179.dkr.ecr.us-east-1.amazonaws.com/ai_image_generation

    - name: Build, tag, and push Docker image
      run: |
        docker build -t 009160047179.dkr.ecr.eu-north-1.amazonaws.com/image-generation-frontend:latest .
        docker tag 009160047179.dkr.ecr.eu-north-1.amazonaws.com/image-generation-frontend:latest
        docker push 009160047179.dkr.ecr.eu-north-1.amazonaws.com/image-generation-frontend:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ai-image-gen --service ai-image --force-new-deployment